// src/testData.js
export const categories = [
    "Dr Reckeweg Tinctures",
    "Dr Reckeweg Tablets",
    "SBL Home",
    "Adel Tinctures",
    "Adel Tablets",
  ];
  export const products = [
    // 40 products for "Dr Reckeweg Tinctures"
        { id: 1, name: "3 Pack of Dr Reckeweg Camphora Q (Mother Tincture) 20ml each", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100", description: "Cures Acidity" },
        { id: 2, name: "3 Pack of Dr Reckeweg Camphora Q (Mother Tincture) 20ml each", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100", description: "Effective Weight Loss Remedy" },
        { id: 3, name: "Product 3", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100", description: "Effective against Cholera. Effective against Allergies. Effective Against Skin Infection" },
        { id: 4, name: "Product 4", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 5, name: "Product 5", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 6, name: "Product 6", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 7, name: "Product 7", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 8, name: "Product 8", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 9, name: "Product 9", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 10, name: "Product 10", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 11, name: "Product 11", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 12, name: "Product 12", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 13, name: "Product 13", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 14, name: "Product 14", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/1-1-200.jpg", price: "100" },
        { id: 15, name: "Product 15", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 16, name: "Product 16", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 17, name: "Product 17", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 18, name: "Product 18", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 19, name: "Product 19", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 20, name: "Product 20", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 21, name: "Product 21", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 22, name: "Product 22", category: "Dr Reckeweg Tinctures", image: "https://cdn.shopify.com/s/files/1/1312/2961/products/45-1-200.jpg", price: "100" },
        { id: 23, name: "Product 23", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/171", price: "100" },
        { id: 24, name: "Product 24", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/172", price: "100" },
        { id: 25, name: "Product 25", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/173", price: "100" },
        { id: 26, name: "Product 26", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/174", price: "100" },
        { id: 27, name: "Product 27", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/175", price: "100" },
        { id: 28, name: "Product 28", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/176", price: "100" },
        { id: 29, name: "Product 29", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/177", price: "100" },
        { id: 30, name: "Product 30", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/178", price: "100" },
        { id: 31, name: "Product 31", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/179", price: "100" },
        { id: 32, name: "Product 32", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/180", price: "100" },
        { id: 33, name: "Product 33", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/181", price: "100" },
        { id: 34, name: "Product 34", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/182", price: "100" },
        { id: 35, name: "Product 35", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/183", price: "100" },
        { id: 36, name: "Product 36", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/184", price: "100" },
        { id: 37, name: "Product 37", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/185", price: "100" },
        { id: 38, name: "Product 38", category: "Dr Reckeweg Tinctures", image: "https://via.placeholder.com/186", price: "100" },
        { id: 41, name: "Product 39", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/150", price: "120" },
        { id: 42, name: "Product 40", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/150", price: "120" },
        { id: 43, name: "Product 41", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/151", price: "121" },
        { id: 44, name: "Product 42", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/152", price: "122" },
        { id: 45, name: "Product 43", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/153", price: "123" },
        { id: 46, name: "Product 44", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/154", price: "124" },
        { id: 47, name: "Product 45", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/155", price: "125" },
        { id: 48, name: "Product 46", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/156", price: "126" },
        { id: 49, name: "Product 47", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/157", price: "127" },
        { id: 50, name: "Product 48", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/158", price: "128" },
        { id: 51, name: "Product 49", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/159", price: "129" },
        { id: 52, name: "Product 50", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/160", price: "130" },
        { id: 53, name: "Product 51", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/161", price: "131" },
        { id: 54, name: "Product 52", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/162", price: "132" },
        { id: 55, name: "Product 53", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/163", price: "133" },
        { id: 56, name: "Product 54", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/164", price: "134" },
        { id: 57, name: "Product 55", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/165", price: "135" },
        { id: 58, name: "Product 56", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/166", price: "136" },
        { id: 59, name: "Product 57", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/167", price: "137" },
        { id: 60, name: "Product 58", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/168", price: "138" },
        { id: 61, name: "Product 59", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/169", price: "139" },
        { id: 62, name: "Product 60", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/170", price: "140" },
        { id: 63, name: "Product 61", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/171", price: "141" },
        { id: 64, name: "Product 62", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/172", price: "142" },
        { id: 65, name: "Product 63", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/173", price: "143" },
        { id: 66, name: "Product 64", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/174", price: "144" },
        { id: 67, name: "Product 65", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/175", price: "145" },
        { id: 68, name: "Product 66", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/176", price: "146" },
        { id: 69, name: "Product 67", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/177", price: "147" },
        { id: 70, name: "Product 68", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/178", price: "148" },
        { id: 71, name: "Product 69", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/179", price: "149" },
        { id: 72, name: "Product 70", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/180", price: "150" },
        { id: 73, name: "Product 71", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/181", price: "151" },
        { id: 74, name: "Product 72", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/182", price: "152" },
        { id: 75, name: "Product 73", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/183", price: "153" },
        { id: 76, name: "Product 74", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/184", price: "154" },
        { id: 77, name: "Product 75", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/185", price: "155" },
        { id: 78, name: "Product 76", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/186", price: "156" },
        { id: 79, name: "Product 77", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/187", price: "157" },
        { id: 80, name: "Product 78", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/188", price: "158" },
        { id: 81, name: "Product 79", category: "Dr Reckeweg Tablets", image: "https://via.placeholder.com/189", price: "159" },
        { id: 82, name: "Product 80", category: "SBL Home", image: "https://via.placeholder.com/150", price: "140" },
        { id: 83, name: "Product 81", category: "SBL Home", image: "https://via.placeholder.com/150", price: "140" },
        { id: 84, name: "Product 82", category: "SBL Home", image: "https://via.placeholder.com/151", price: "141" },
        { id: 85, name: "Product 83", category: "SBL Home", image: "https://via.placeholder.com/152", price: "142" },
        { id: 86, name: "Product 84", category: "SBL Home", image: "https://via.placeholder.com/153", price: "143" },
        { id: 87, name: "Product 85", category: "SBL Home", image: "https://via.placeholder.com/154", price: "144" },
        { id: 88, name: "Product 86", category: "SBL Home", image: "https://via.placeholder.com/155", price: "145" },
        { id: 89, name: "Product 87", category: "SBL Home", image: "https://via.placeholder.com/156", price: "146" },
        { id: 90, name: "Product 88", category: "SBL Home", image: "https://via.placeholder.com/157", price: "147" },
        { id: 91, name: "Product 89", category: "SBL Home", image: "https://via.placeholder.com/158", price: "148" },
        { id: 92, name: "Product 90", category: "SBL Home", image: "https://via.placeholder.com/159", price: "149" },
        { id: 93, name: "Product 91", category: "SBL Home", image: "https://via.placeholder.com/160", price: "150" },
        { id: 94, name: "Product 92", category: "SBL Home", image: "https://via.placeholder.com/161", price: "151" },
        { id: 95, name: "Product 93", category: "SBL Home", image: "https://via.placeholder.com/162", price: "152" },
        { id: 96, name: "Product 94", category: "SBL Home", image: "https://via.placeholder.com/163", price: "153" },
        { id: 97, name: "Product 95", category: "SBL Home", image: "https://via.placeholder.com/164", price: "154" },
        { id: 98, name: "Product 96", category: "SBL Home", image: "https://via.placeholder.com/165", price: "155" },
        { id: 99, name: "Product 97", category: "SBL Home", image: "https://via.placeholder.com/166", price: "156" },
        { id: 100, name: "Product 98", category: "SBL Home", image: "https://via.placeholder.com/167", price: "157" },
        { id: 101, name: "Product 99", category: "SBL Home", image: "https://via.placeholder.com/168", price: "158" },
        { id: 102, name: "Product 100", category: "SBL Home", image: "https://via.placeholder.com/169", price: "159" },
        { id: 103, name: "Product 101", category: "SBL Home", image: "https://via.placeholder.com/170", price: "160" },
        { id: 104, name: "Product 102", category: "SBL Home", image: "https://via.placeholder.com/171", price: "161" },
        { id: 105, name: "Product 103", category: "SBL Home", image: "https://via.placeholder.com/172", price: "162" },
        { id: 106, name: "Product 104", category: "SBL Home", image: "https://via.placeholder.com/173", price: "163" },
        { id: 107, name: "Product 105", category: "SBL Home", image: "https://via.placeholder.com/174", price: "164" },
        { id: 108, name: "Product 106", category: "SBL Home", image: "https://via.placeholder.com/175", price: "165" },
        { id: 109, name: "Product 107", category: "SBL Home", image: "https://via.placeholder.com/176", price: "166" },
        { id: 110, name: "Product 108", category: "SBL Home", image: "https://via.placeholder.com/177", price: "167" },
        { id: 111, name: "Product 109", category: "SBL Home", image: "https://via.placeholder.com/178", price: "168" },
        { id: 112, name: "Product 110", category: "SBL Home", image: "https://via.placeholder.com/179", price: "169" },
        { id: 113, name: "Product 111", category: "SBL Home", image: "https://via.placeholder.com/180", price: "170" },
        { id: 114, name: "Product 112", category: "SBL Home", image: "https://via.placeholder.com/181", price: "171" },
        { id: 115, name: "Product 113", category: "SBL Home", image: "https://via.placeholder.com/182", price: "172" },
        { id: 116, name: "Product 114", category: "SBL Home", image: "https://via.placeholder.com/183", price: "173" },
        { id: 117, name: "Product 115", category: "SBL Home", image: "https://via.placeholder.com/184", price: "174" },
        { id: 118, name: "Product 116", category: "SBL Home", image: "https://via.placeholder.com/185", price: "175" },
        { id: 119, name: "Product 117", category: "SBL Home", image: "https://via.placeholder.com/186", price: "176" },
        { id: 120, name: "Product 118", category: "SBL Home", image: "https://via.placeholder.com/187", price: "177" },
        { id: 121, name: "Product 119", category: "SBL Home", image: "https://via.placeholder.com/188", price: "178" },
        { id: 122, name: "Product 120", category: "Adel Tinctures", image: "https://via.placeholder.com/150", price: "160" },
        { id: 123, name: "Product 121", category: "Adel Tinctures", image: "https://via.placeholder.com/150", price: "160" },
        { id: 124, name: "Product 122", category: "Adel Tinctures", image: "https://via.placeholder.com/151", price: "161" },
        { id: 125, name: "Product 123", category: "Adel Tinctures", image: "https://via.placeholder.com/152", price: "162" },
        { id: 126, name: "Product 124", category: "Adel Tinctures", image: "https://via.placeholder.com/153", price: "163" },
        { id: 127, name: "Product 125", category: "Adel Tinctures", image: "https://via.placeholder.com/154", price: "164" },
        { id: 128, name: "Product 126", category: "Adel Tinctures", image: "https://via.placeholder.com/155", price: "165" },
        { id: 129, name: "Product 127", category: "Adel Tinctures", image: "https://via.placeholder.com/156", price: "166" },
        { id: 130, name: "Product 128", category: "Adel Tinctures", image: "https://via.placeholder.com/157", price: "167" },
        { id: 131, name: "Product 129", category: "Adel Tinctures", image: "https://via.placeholder.com/158", price: "168" },
        { id: 132, name: "Product 130", category: "Adel Tinctures", image: "https://via.placeholder.com/159", price: "169" },
        { id: 133, name: "Product 131", category: "Adel Tinctures", image: "https://via.placeholder.com/160", price: "170" },
        { id: 134, name: "Product 132", category: "Adel Tinctures", image: "https://via.placeholder.com/161", price: "171" },
        { id: 135, name: "Product 133", category: "Adel Tinctures", image: "https://via.placeholder.com/162", price: "172" },
        { id: 136, name: "Product 134", category: "Adel Tinctures", image: "https://via.placeholder.com/163", price: "173" },
        { id: 137, name: "Product 135", category: "Adel Tinctures", image: "https://via.placeholder.com/164", price: "174" },
        { id: 138, name: "Product 136", category: "Adel Tinctures", image: "https://via.placeholder.com/165", price: "175" },
        { id: 139, name: "Product 137", category: "Adel Tinctures", image: "https://via.placeholder.com/166", price: "176" },
        { id: 140, name: "Product 138", category: "Adel Tinctures", image: "https://via.placeholder.com/167", price: "177" },
        { id: 141, name: "Product 139", category: "Adel Tinctures", image: "https://via.placeholder.com/168", price: "178" },
        { id: 142, name: "Product 140", category: "Adel Tinctures", image: "https://via.placeholder.com/169", price: "179" },
        { id: 143, name: "Product 141", category: "Adel Tinctures", image: "https://via.placeholder.com/170", price: "180" },
        { id: 144, name: "Product 142", category: "Adel Tinctures", image: "https://via.placeholder.com/171", price: "181" },
        { id: 145, name: "Product 143", category: "Adel Tinctures", image: "https://via.placeholder.com/172", price: "182" },
        { id: 146, name: "Product 144", category: "Adel Tinctures", image: "https://via.placeholder.com/173", price: "183" },
        { id: 147, name: "Product 145", category: "Adel Tinctures", image: "https://via.placeholder.com/174", price: "184" },
        { id: 148, name: "Product 146", category: "Adel Tinctures", image: "https://via.placeholder.com/175", price: "185" },
        { id: 149, name: "Product 147", category: "Adel Tinctures", image: "https://via.placeholder.com/176", price: "186" },
        { id: 150, name: "Product 148", category: "Adel Tinctures", image: "https://via.placeholder.com/177", price: "187" },
        { id: 151, name: "Product 149", category: "Adel Tinctures", image: "https://via.placeholder.com/178", price: "188" },
        { id: 152, name: "Product 150", category: "Adel Tinctures", image: "https://via.placeholder.com/179", price: "189" },
        { id: 153, name: "Product 151", category: "Adel Tinctures", image: "https://via.placeholder.com/180", price: "190" },
        { id: 154, name: "Product 152", category: "Adel Tinctures", image: "https://via.placeholder.com/181", price: "191" },
        { id: 155, name: "Product 153", category: "Adel Tinctures", image: "https://via.placeholder.com/182", price: "192" },
        { id: 156, name: "Product 154", category: "Adel Tinctures", image: "https://via.placeholder.com/183", price: "193" },
        { id: 157, name: "Product 155", category: "Adel Tinctures", image: "https://via.placeholder.com/184", price: "194" },
        { id: 158, name: "Product 156", category: "Adel Tinctures", image: "https://via.placeholder.com/185", price: "195" },
        { id: 159, name: "Product 157", category: "Adel Tinctures", image: "https://via.placeholder.com/186", price: "196" },
        { id: 160, name: "Product 158", category: "Adel Tinctures", image: "https://via.placeholder.com/187", price: "197" },
        { id: 161, name: "Product 159", category: "Adel Tinctures", image: "https://via.placeholder.com/188", price: "198" },
        { id: 162, name: "Product 160", category: "Adel Tablets", image: "https://via.placeholder.com/150", price: "180" },
        { id: 163, name: "Product 161", category: "Adel Tablets", image: "https://via.placeholder.com/150", price: "180" },
        { id: 164, name: "Product 162", category: "Adel Tablets", image: "https://via.placeholder.com/151", price: "181" },
        { id: 165, name: "Product 163", category: "Adel Tablets", image: "https://via.placeholder.com/152", price: "182" },
        { id: 166, name: "Product 164", category: "Adel Tablets", image: "https://via.placeholder.com/153", price: "183" },
        { id: 167, name: "Product 165", category: "Adel Tablets", image: "https://via.placeholder.com/154", price: "184" },
        { id: 168, name: "Product 166", category: "Adel Tablets", image: "https://via.placeholder.com/155", price: "185" },
        { id: 169, name: "Product 167", category: "Adel Tablets", image: "https://via.placeholder.com/156", price: "186" },
        { id: 170, name: "Product 168", category: "Adel Tablets", image: "https://via.placeholder.com/157", price: "187" },
        { id: 171, name: "Product 169", category: "Adel Tablets", image: "https://via.placeholder.com/158", price: "188" },
        { id: 172, name: "Product 170", category: "Adel Tablets", image: "https://via.placeholder.com/159", price: "189" },
        { id: 173, name: "Product 171", category: "Adel Tablets", image: "https://via.placeholder.com/160", price: "190" },
        { id: 174, name: "Product 172", category: "Adel Tablets", image: "https://via.placeholder.com/161", price: "191" },
        { id: 175, name: "Product 173", category: "Adel Tablets", image: "https://via.placeholder.com/162", price: "192" },
        { id: 176, name: "Product 174", category: "Adel Tablets", image: "https://via.placeholder.com/163", price: "193" },
        { id: 177, name: "Product 175", category: "Adel Tablets", image: "https://via.placeholder.com/164", price: "194" },
        { id: 178, name: "Product 176", category: "Adel Tablets", image: "https://via.placeholder.com/165", price: "195" },
        { id: 179, name: "Product 177", category: "Adel Tablets", image: "https://via.placeholder.com/166", price: "196" },
        { id: 180, name: "Product 178", category: "Adel Tablets", image: "https://via.placeholder.com/167", price: "197" },
        { id: 181, name: "Product 179", category: "Adel Tablets", image: "https://via.placeholder.com/168", price: "198" },
        { id: 182, name: "Product 180", category: "Adel Tablets", image: "https://via.placeholder.com/169", price: "199" },
        { id: 183, name: "Product 181", category: "Adel Tablets", image: "https://via.placeholder.com/170", price: "200" },
        { id: 184, name: "Product 182", category: "Adel Tablets", image: "https://via.placeholder.com/171", price: "201" },
        { id: 185, name: "Product 183", category: "Adel Tablets", image: "https://via.placeholder.com/172", price: "202" },
        { id: 186, name: "Product 184", category: "Adel Tablets", image: "https://via.placeholder.com/173", price: "203" },
        { id: 187, name: "Product 185", category: "Adel Tablets", image: "https://via.placeholder.com/174", price: "204" },
        { id: 188, name: "Product 186", category: "Adel Tablets", image: "https://via.placeholder.com/175", price: "205" },
        { id: 189, name: "Product 187", category: "Adel Tablets", image: "https://via.placeholder.com/176", price: "206" },
        { id: 190, name: "Product 188", category: "Adel Tablets", image: "https://via.placeholder.com/177", price: "207" },
        { id: 191, name: "Product 189", category: "Adel Tablets", image: "https://via.placeholder.com/178", price: "208" },
        { id: 192, name: "Product 190", category: "Adel Tablets", image: "https://via.placeholder.com/179", price: "209" },
        { id: 193, name: "Product 191", category: "Adel Tablets", image: "https://via.placeholder.com/180", price: "210" },
        { id: 194, name: "Product 192", category: "Adel Tablets", image: "https://via.placeholder.com/181", price: "211" },
        { id: 195, name: "Product 193", category: "Adel Tablets", image: "https://via.placeholder.com/182", price: "212" },
        { id: 196, name: "Product 194", category: "Adel Tablets", image: "https://via.placeholder.com/183", price: "213" },
        { id: 197, name: "Product 195", category: "Adel Tablets", image: "https://via.placeholder.com/184", price: "214" },
        { id: 198, name: "Product 196", category: "Adel Tablets", image: "https://via.placeholder.com/185", price: "215" },
        { id: 199, name: "Product 197", category: "Adel Tablets", image: "https://via.placeholder.com/186", price: "216" },
        { id: 200, name: "Product 198", category: "Adel Tablets", image: "https://via.placeholder.com/187", price: "217" },
        { id: 201, name: "Product 199", category: "Adel Tablets", image: "https://via.placeholder.com/188", price: "218" },
];